# Generated by Django 5.2.17 on 2026-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name note')),
                ('brief', models.TextField(verbose_name='brief note')),
                ('text', models.TextField(verbose_name='text note')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data note')),
            ],
        ),
    ]
